# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '-Dorg.gradle.warning.mode=all'
    tasks: 'assembleDebug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false


- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'upload-keystore.jks'
    apksignerKeystorePassword: '$(KeyStorePass)'
    apksignerKeystoreAlias: 'upload'
    apksignerKeyPassword: '$(KeyPass)'
    zipalign: false

- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'App center'
    appSlug: 'ever0035/HealthApp'
    appFile: '**/app-debug.apk'
    releaseNotesOption: 'input'
    releaseNotesInput: '.'
    distributionGroupId: '6c809db3-8b8f-47a4-b7da-5c1111f5308f'